{-# LANGUAGE OverloadedStrings #-}

-- LLM-driven classifier fallback. Used by Hybrid when rule confidence is low.
-- Reads DEEPSEEK_API_KEY from env, builds a zero-shot prompt anchored on
-- archetype definitions, parses the JSON reply.
module HaskellTester.Classifier.LLM
    ( classify
    , classifyRuntime    -- NEW: classify from README + baseline probes (not from sparse summary)
    , buildPrompt        -- exposed for testing / debugging
    , loadFewShot
    ) where

import Control.Exception (catch, SomeException)
import qualified Data.Aeson as A
import qualified Data.Aeson.KeyMap as KM
import qualified Data.ByteString as BS
import qualified Data.ByteString.Lazy as BL
import qualified Data.ByteString.Lazy.Char8 as BLC
import Data.Map.Strict (Map)
import qualified Data.Map.Strict as Map
import Data.Text (Text)
import qualified Data.Text as T
import qualified Data.Text.Encoding as TE
import qualified Data.Vector as V
import System.Environment (lookupEnv)

import HaskellTester.EmbeddedData (embeddedFewShot)
import HaskellTester.LLM.Deepseek
import HaskellTester.Probe.Baseline (BaselineResult (..), BaselineSignals (..), renderSignals)
import HaskellTester.Types


-- One short definition line per archetype, matching what subagents converged on.
archetypeDefs :: [(Archetype, Text)]
archetypeDefs =
    [ (ByteExactGolden,            "stdout.eq or other.eq dominates; tests compare full bytes against golden fixtures; docstrings cite 'Golden files'.")
    , (CliSurfaceAndExitCode,      "returncode.eq leads + stdout/stderr.contains on flag/help/error tokens; binary judged by exit semantics + diagnostic substrings.")
    , (FilesystemSideEffect,       "other.truthy/contains/eq on file artifacts; grader inspects produced filesystem state, not stdout.")
    , (TuiScreenSnapshot,          "Interactive TUI; assertions check captured screen state via 'other' + golden screens; returncode.eq is unusually low.")
    , (LinterDiagnostic,           "Static analyzer/linter; assertions check specific diagnostic codes fire; expected literals are rule IDs.")
    , (NumericTolerance,           "other.gt/ge/lt/le bounds dominate; non-deterministic or numeric output validated by inequalities.")
    , (OrchestrationDrivenWatcher, "Tool needs multi-step orchestration via popen + sleep + file/state mutation; popen_calls > 0.")
    , (MassiveFixtureSuite,        "Single task with thousands of parameterized fixture tests sharing a template docstring.")
    ]


-- Load few-shot examples from data/fewshot_examples.json (generated by gen_fewshot.py).
-- Returns Map "ArchetypeName" -> [example summary JSON Value].
loadFewShot :: FilePath -> IO (Map Text [A.Value])
loadFewShot dataDir = do
    bs <- BL.readFile (dataDir <> "/fewshot_examples.json")
    decodeFewShotBytes (BL.toStrict bs)


-- Load few-shot examples directly from the binary's embedded data (no disk I/O).
loadFewShotEmbedded :: IO (Map Text [A.Value])
loadFewShotEmbedded =
    decodeFewShotBytes embeddedFewShot


decodeFewShotBytes :: BS.ByteString -> IO (Map Text [A.Value])
decodeFewShotBytes bs = case A.decodeStrict bs :: Maybe A.Object of
    Nothing -> pure Map.empty
    Just o  -> pure $ Map.fromList
        [ (T.pack (show k), V.toList vec)
        | (k, A.Array vec) <- KM.toList o
        ]


-- Render a single few-shot example into terse text the LLM can read.
renderExample :: A.Value -> Text
renderExample v = case v of
    A.Object o -> T.unlines $ concat
        [ [ "  n_tests: "      <> tshowVal (KM.lookup "n_tests" o)
          , "  popen_calls: "  <> tshowVal (KM.lookup "popen_calls" o)
          ]
        , [ "  signals: " <> renderKV (KM.lookup "assertion_distribution" o) ]
        , [ "  expected_value_samples: " <> renderArr (KM.lookup "expected_value_samples" o) ]
        , [ "  docstring sample: " <> renderArr (KM.lookup "docstring_samples" o) ]
        , [ "  test_files: " <> renderArr (KM.lookup "test_files" o) ]
        ]
    _ -> ""
  where
    tshowVal (Just (A.Number n)) = T.pack (show n)
    tshowVal (Just x)            = T.pack (show x)
    tshowVal Nothing             = "?"
    renderKV (Just (A.Object o)) =
        T.intercalate ", " [ k <> "=" <> tshowVal (Just v') | (k', v') <- KM.toList o
                           , let k = T.pack (show k') ]
    renderKV _ = ""
    renderArr (Just (A.Array v')) =
        T.intercalate "; " [ s | A.String s <- V.toList v' ]
    renderArr _ = ""


-- Render all few-shot examples into a single prompt section.
renderFewShot :: Map Text [A.Value] -> Text
renderFewShot fs = T.unlines $ concat
    [ [ "### " <> arch ] <> map renderExample examples <> [ "" ]
    | (arch, examples) <- Map.toAscList fs
    ]


-- Compose the user prompt around a task summary, with few-shot anchors.
buildPrompt :: Map Text [A.Value] -> TaskSummary -> [Message]
buildPrompt fewShot s =
    [ Message "system"
        ("You are classifying ProgramBench grader task summaries into one of 8 canonical archetypes.\n\n"
         <> "Archetypes:\n"
         <> T.intercalate "\n"
              [ "- " <> archetypeName a <> ": " <> def | (a, def) <- archetypeDefs ]
         <> "\n\nDECISION ALGORITHM (apply IN ORDER — first match wins):\n\n"
         <> "  Step 1. If popen_calls >= 5 → OrchestrationDrivenWatcher. STOP.\n"
         <> "  Step 2. If n_tests >= 1500 AND docstring_samples are template-repeated → MassiveFixtureSuite. STOP.\n"
         <> "  Step 3. If (other.gt + other.ge + other.lt + other.le) >= 0.20 → NumericTolerance. STOP.\n"
         <> "  Step 4. If stdout.eq >= 0.15 → ByteExactGolden. STOP. (do NOT downgrade to CLI even if rc.eq is also high)\n"
         <> "  Step 5. If other.eq >= 0.20 AND docstrings mention 'Golden files'/'.golden' → ByteExactGolden. STOP.\n"
         <> "  Step 6. If test_files mention 'lint'/'checker' AND expected_value_samples look like rule IDs (e.g. 'MD024', 'W23', 'badCond') → LinterDiagnostic. STOP.\n"
         <> "  Step 7. If returncode.eq < 0.15 AND (other.contains + other.truthy + other.eq) >= 0.45 AND test_files mention 'tui'/'interactive'/'screen' → TuiScreenSnapshot. STOP.\n"
         <> "  Step 8. If (other.truthy + other.contains) >= 0.30 AND stdout.eq < 0.10 AND expected_value_samples look like FILE PATHS (not flag tokens) → FilesystemSideEffect. STOP.\n"
         <> "  Step 9. DEFAULT: CliSurfaceAndExitCode (returncode.eq leads + flag/help/error substrings).\n\n"
         <> "BEFORE ANSWERING:\n"
         <> "  - Identify the SINGLE DOMINANT numeric signal (the assertion_distribution entry with highest value).\n"
         <> "  - Walk through the steps above explicitly until one matches.\n"
         <> "  - Cite both the matching step number AND the numeric value in your reason.\n\n"
         <> "Few-shot reference patterns (abstract signal shapes, NOT lookups):\n\n"
         <> renderFewShot fewShot
         <> "\nReply with strict JSON only: {\"archetype\":\"<Name>\",\"reason\":\"step N: <signal>=<value>\"}")
    , Message "user"
        ("Task summary to classify:\n" <> renderSummary s
         <> "\n\nApply the decision algorithm. Identify the dominant signal first, then walk the steps.")
    ]


-- Compact, LLM-friendly rendering of TaskSummary (avoid sending huge JSON).
renderSummary :: TaskSummary -> Text
renderSummary s = T.unlines $ concat
    [ [ "task_id: "       <> tsTaskId s
      , "n_tests: "       <> tshow (tsNTests s)
      , "popen_calls: "   <> tshow (tsPopenCalls s)
      , "assertion_distribution:"
      ]
    , [ "  " <> k <> ": " <> tshow v | (k, v) <- Map.toAscList (tsAssertionDistribution s) ]
    , [ "invocation_patterns:" ]
    , [ "  " <> k <> ": " <> tshow v | (k, v) <- Map.toAscList (tsInvocationPatterns s) ]
    , [ "expected_value_samples (first 8):" ]
    , [ "  - " <> sample | sample <- take 8 (tsExpectedValueSamples s) ]
    , [ "docstring_samples (first 3):" ]
    , [ "  - " <> T.take 200 d | d <- take 3 (tsDocstringSamples s) ]
    , [ "test_files (first 8):" ]
    , [ "  - " <> f | f <- take 8 (tsTestFiles s) ]
    ]
  where
    tshow x = T.pack (show x)


-- Parse the LLM JSON reply into a ClassifyResult.
parseReply :: Text -> ClassifyResult
parseReply raw =
    case A.decode (BL.fromStrict (TE.encodeUtf8 (extractJson raw))) of
        Just (A.Object o) ->
            let archStr = case KM.lookup "archetype" o of
                            Just (A.String t) -> t
                            _                 -> "CliSurfaceAndExitCode"
                reason  = case KM.lookup "reason" o of
                            Just (A.String t) -> t
                            _                 -> ""
            in ClassifyResult
                   { crArchetype  = maybe CliSurfaceAndExitCode id (archetypeFromName archStr)
                   , crConfidence = 0.85
                   , crReasons    = ["LLM: " <> reason]
                   , crSource     = LLMFallback
                   }
        _ -> ClassifyResult
                 { crArchetype  = CliSurfaceAndExitCode
                 , crConfidence = 0.40
                 , crReasons    = ["LLM parse failed", "raw: " <> T.take 200 raw]
                 , crSource     = LLMFallback
                 }
  where
    -- Strip code fences / surrounding prose, keep from first '{' to last '}' inclusive.
    extractJson t = T.dropWhileEnd (/= '}') (T.dropWhile (/= '{') t)


classify :: TaskSummary -> IO ClassifyResult
classify summary = do
    mKey <- lookupEnv "DEEPSEEK_API_KEY"
    case mKey of
        Nothing  -> pure ClassifyResult
            { crArchetype  = CliSurfaceAndExitCode
            , crConfidence = 0.40
            , crReasons    = ["DEEPSEEK_API_KEY not set"]
            , crSource     = LLMFallback
            }
        Just key -> do
            fewShot <- loadFewShotEmbedded
            let req = defaultRequest (buildPrompt fewShot summary)
            (parseReply <$> callChat (T.pack key) req)
                `catch` \(e :: SomeException) -> pure ClassifyResult
                    { crArchetype  = CliSurfaceAndExitCode
                    , crConfidence = 0.40
                    , crReasons    = ["LLM error: " <> T.pack (show e)]
                    , crSource     = LLMFallback
                    }


-- Runtime classifier: drives on README + baseline probe outputs,
-- not on the sparse TaskSummary (which can't reflect runtime evidence).
classifyRuntime :: Text -> BaselineResult -> IO ClassifyResult
classifyRuntime readme baseline = do
    mKey <- lookupEnv "DEEPSEEK_API_KEY"
    case mKey of
        Nothing -> pure ClassifyResult
            { crArchetype  = CliSurfaceAndExitCode
            , crConfidence = 0.40
            , crReasons    = ["DEEPSEEK_API_KEY not set"]
            , crSource     = LLMFallback
            }
        Just key -> do
            fewShot <- loadFewShotEmbedded
            let req = defaultRuntimeRequest (buildRuntimePrompt fewShot readme baseline)
            (parseReply <$> callChat (T.pack key) req)
                `catch` \(e :: SomeException) -> pure ClassifyResult
                    { crArchetype  = CliSurfaceAndExitCode
                    , crConfidence = 0.40
                    , crReasons    = ["LLM error: " <> T.pack (show e)]
                    , crSource     = LLMFallback
                    }


-- temperature=0 + slightly higher max_tokens for the runtime classifier.
defaultRuntimeRequest :: [Message] -> ChatRequest
defaultRuntimeRequest msgs = (defaultRequest msgs)
    { reqMaxTokens   = 400
    , reqTemperature = 0.0
    }


-- Prompt designed around RUNTIME signals — what we actually have at probe time.
-- Stops the LLM defaulting to CliSurface just because it can't see assertion_distribution.
buildRuntimePrompt :: Map Text [A.Value] -> Text -> BaselineResult -> [Message]
buildRuntimePrompt fewShot readme baseline =
    [ Message "system"
        ( "You are classifying a black-box binary into one of 8 archetypes from a known taxonomy.\n\n"
          <> "Unlike a graded-test summary, you see ONLY runtime signals (README, baseline probe outputs).\n"
          <> "You must infer archetype from how the binary BEHAVES, not from grader assertion distributions.\n\n"
          <> "Archetypes:\n"
          <> T.intercalate "\n" [ "- " <> archetypeName a <> ": " <> def | (a, def) <- archetypeDefs ]
          <> "\n\nRUNTIME DECISION ALGORITHM (apply in order):\n"
          <> "  Step 1. binary_format mentions 'ncurses'/'libncurses' OR README emphasises TUI → TuiScreenSnapshot.\n"
          <> "  Step 2. README emphasises file manipulation (rename/move/edit/create files) AND no_args_behavior is not 'shows-help' → FilesystemSideEffect.\n"
          <> "  Step 3. README describes structured I/O transform (json/yaml/csv/text in → bytes out, exact format) → ByteExactGolden.\n"
          <> "  Step 4. README describes a linter/static-analyzer that emits diagnostic codes (e.g. MD001, lint rule ids) → LinterDiagnostic.\n"
          <> "  Step 5. README describes a long-running watcher/looper (file watcher, command repeater, polling) → OrchestrationDrivenWatcher.\n"
          <> "  Step 6. README describes numeric / scientific output with tolerances → NumericTolerance.\n"
          <> "  Step 7. README is huge with parameterised fixture suites (rare at runtime) → MassiveFixtureSuite.\n"
          <> "  Step 8. DEFAULT: CliSurfaceAndExitCode.\n\n"
          <> "When uncertain between ByteExactGolden and CliSurfaceAndExitCode, lean to ByteExactGolden if README shows a transform pattern (input → exact output).\n\n"
          <> "Few-shot reference patterns (these are dev-time signal shapes — adapt the spirit, not the exact thresholds):\n\n"
          <> renderFewShot fewShot
          <> "\nReply with strict JSON only: {\"archetype\":\"<Name>\",\"reason\":\"step N: <observation>\"}"
        )
    , Message "user"
        ( "README excerpt:\n```\n" <> T.take 4000 readme <> "\n```\n\n"
          <> "Baseline probe signals:\n```\n" <> renderSignals (brSignals baseline) <> "```\n\n"
          <> "Probe outputs (truncated):\n```\n"
          <> T.intercalate "\n---\n" [ "$ " <> cmd <> "\n" <> T.take 400 out
                                     | (cmd, out) <- brProbes baseline ]
          <> "\n```\n\n"
          <> "Apply the runtime decision algorithm. Pick exactly ONE archetype."
        )
    ]
